# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170405_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='senha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('confirm_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('Password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.senha')),
                ('nick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.usuario')),
            ],
        ),
    ]
