# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_senha_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nick',
            field=models.CharField(max_length=10),
        ),
    ]
