# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170405_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
