# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
